### ISSUE TITLE
Type inconsistency in the syscall headers

### ISSUE THREAD

**Issue by gbl08ma** [Jonimoose/libfxcg#19]
There are several syscall headers which expect different types for the arguments, when compared to Simon Lothar's documentation and to the Prizm Wiki. For example:
- PrintMini: is the third argument a `const char*` (libfxcg) or a `(const?) unsigned char*` (Simon, wiki)?
- Bfile_StrToName_ncpy: is the second argument a `const char*` (libfxcg) or a `(const?) unsigned char*` (Simon, wiki)?

I see that at least some of these changes took place on commit ebf41b847d5b036d9992b5f056b652999d479207. The commit messages leads me to believe these were changes made by AHelper, but when one sees the current HEAD of AHelper's fork of libfxcg, the arguments in question have the type `unsigned char*`.

I'm having trouble understanding which header is correct, and if the signed versions of the headers are right, I'd like to know the reason for the changes from an unsigned to a signed char pointer, as the original reverse-engineering work mentions a unsigned char pointer.

**Comment by dr-carlos** [comment]
> Signedness is important only if you're doing arithmetic, particularly signed comparisons or multiplication/division by negative numbers. AFAICT none of the operations that would be meaningfully affected by signedness are reasonable to use on strings anyway, it really doesn't matter. The ABI specifies the signed and unsigned variants of `char` are both 8 bits, so that doesn't change anything either.
> 
> Given there's no sane use case for `signed char` strings and it requires more typing to make it `signed`, I see no reason to change the current definition.
So, should all `unsigned (const) char*`s in the syscall headers be changed to `(const) char`, i.e. making them signed?

**Comment by tari** [comment]
At this point I'd be more inclined to leave them as-is rather than change things that people are already using (unless the status quo is an annoyance because it causes warnings in the typical use case).

**Comment by dr-carlos** [comment]
Yep, that makes sense. So does anything need to be done for this issue?
