### ISSUE TITLE
strtol is broken

### ISSUE THREAD

**Issue by gbl08ma** [Jonimoose/libfxcg#29]
`strtol`, and consequently `atoi` and other functions, are broken. I noticed the problem just as I tried to use upstream libfxcg to compile Utilities. It compiles fine, but at run time the things that depend on `strtol` behave unexpectedly (the code works fine when `atoi` is provided as syscall, or in the same way it was provided before - don't know how exactly).

Using other `strtol` implementations such as [this one](http://www.leidinger.net/FreeBSD/dox/libkern/html/d5/d65/strtol_8c_source.html) works fine.

**Comment by dr-carlos** [comment]
> `strtol`, and consequently `atoi` and other functions, are broken. I noticed the problem just as I tried to use upstream libfxcg to compile Utilities. It compiles fine, but at run time the things that depend on `strtol` behave unexpectedly (the code works fine when `atoi` is provided as syscall, or in the same way it was provided before - don't know how exactly).
> 
> Using other `strtol` implementations such as [this one](http://www.leidinger.net/FreeBSD/dox/libkern/html/d5/d65/strtol_8c_source.html) works fine.

 Is fixing this as simple as replacing the current implementation with the FreeBSD one?

**Comment by tari** [comment]
Can't be certain because it's unclear what exactly is broken, but presumably dropping in a mature one from elsewhere would fix it; yes.

**Comment by dr-carlos** [comment]
#82 Closes this.
