### ISSUE TITLE
libc FILE* behavior for standard streams

### ISSUE THREAD

**Issue by tari** [Jonimoose/libfxcg#30]
Discussed somewhat in #22. It would be more user-friendly to have the standard streams have some way to go do the display (and possibly read from the keyboard), but we need to decide on a design.

Offhand, I think it might be reasonable to have `stderr` go to serial (as it does now) and `stdout` to the screen, possibly to serial as well. Messages that should be seen by users can go to `stdout` and be reliably seen, while detailed diagnostics go to `stderr` where they're visible with some effort if needed.

This opens up a number of questions on how such output should interact with the text-display syscalls, where the easiest solution is to ignore them.

**Comment by Heath123** [comment]
Is there a good way to view stderr messages with just a USB cable?

**Comment by dr-carlos** [comment]
#97 Closes this issue.
