### ISSUE TITLE
Including into the sdk

### ISSUE THREAD

**Issue by fXXa** [Jonimoose/libfxcg#36]
Can someone tell me how to include this into the prizm Sdk?

**Comment by tari** [comment]
I've quietly [been doing some work on building complete packages again](https://github.com/tari/libfxcg/actions/runs/73120372), so as [I see you're trying to just get started](https://www.cemetech.net/forum/viewtopic.php?p=285092#285092), I've built a quick release that you can try:

https://github.com/tari/libfxcg/releases/tag/beta-20200408

The includes all the tools, so you can forget anything else you've read about getting a compiler and updating libfxcg; just unpack that release and use it.
