### ISSUE TITLE
Syscall aliases are weird

### ISSUE THREAD

**Issue by tari** [Jonimoose/libfxcg#43]
Currently we preprocessor define malloc and friends to sys_malloc which is reasonable because somebody might want to provide their own, but it's wonky.

The library should provide weak alises for these functions intead: `__attribute__(weak, alias(foo))`.

**Comment by dr-carlos** [comment]
I am trying to do this, but after removing the functions from stdlib.c and adding `__attrubte__`s to the functions in stdlib.h, it doesn't compile.

Example (inside include/stdlib.h):
```
#include <fxcg/heap.h>
void free(void *p) __attribute__ ((weak, alias ("sys_free")));
```

Compiles with the error 'free' aliased to undefined symbol 'sys_free'.

**Comment by tari** [comment]
That sounds like a linker error. What's the exact output you get?

The documentation for the `alias` attribute suggests you need to use a mangled name, in which case it would be `_sys_free`: that might be all you need.

**Comment by dr-carlos** [comment]
> That sounds like a linker error. What's the exact output you get?
> 
> ~The documentation for the `alias` attribute suggests you need to use a mangled name, in which case it would be `_sys_free`: that might be ayall you need.~
> 
> It also says:
> 
> > It is an error if `__f` is not defined in the same translation unit
> 
> in which case we either need to figure out the assembler directives to emit a weak alias (if it's even supported) or figure out how to make a syscall work in a C file (seems doable with extended inline assembly, which might be better overall).

I assumed this would be the issue.
What syscall are you referring to?

**Comment by tari** [comment]
I think the `sys_` versions could be put in the same translation unit by defining them with inline assembly; I'd rather try to do that than remove the swappability.

**Comment by dr-carlos** [comment]
> I think the `sys_` versions could be put in the same translation unit by defining them with inline assembly; I'd rather try to do that than remove the swappability.

I'm not very familiar with (inline or not) assembly, but I tried inserting the syscalls using __asm__ before the aliases.
Unfortunately, gcc still complains that `'free' aliased to undefined symbol '_sys_free'`.

I also tried defining the functions anyway and seeing whether the syscall ends up being run instead - but this just runs the placeholder functions that I added.

In case you're wondering, this is the asm I used to try and define the syscalls:
```
__asm__ (".text; .align 2; .global _sys_free; .global _sys_malloc ; .global _sys_realloc ; _sys_free: mov.l sc_addr, r2 ; mov.l 1f, r0 ; jmp @r2 ; nop ; 1: .long 0x1F42 ; _sys_malloc: mov.l sc_addr, r2 ; mov.l 1f, r0 ; jmp @r2 ; nop ; 1: .long 0x1F44 ; _sys_realloc: mov.l sc_addr, r2 ; mov.l 1f, r0 ; jmp @r2 ; nop ; 1: .long 0x1F46 ; sc_addr: .long 0x80020070");
```

**Comment by tari** [comment]
This appears to work (prototyped with an x86 target, but should translate fine to SH):

```c
#include <stdlib.h>

__attribute__((naked)) void *sys_free() {
    __asm__ volatile(
        " movq %0, %%rcx\n"
        " movl %1, %%eax\n"
        " jmp *%%rcx"
        : /* No outputs */
        : "i"(0x80020070), "i"(0x1f42)
    );
}

void free(void *p) __attribute__((weak, alias("sys_free")));

int main() {
    free(NULL);
    return 0;
}
```

**Comment by dr-carlos** [comment]
Okay, they seem to be working now:
```
void alias_free() {
	__asm__ volatile(
		"mov.l sc_addr_f, r2; "
		"mov.l 1f, r0; "
		"jmp @r2; "
		"nop; "
		"1: .long 0x1f42 \n"
		"sc_addr_f: .long 0x80020070"
	);
}

void alias_malloc() {
	__asm__ volatile(
		"mov.l sc_addr_m, r2; "
		"mov.l 2f, r0; "
		"jmp @r2; "
		"nop; "
		"2: .long 0x1f44 \n"
		"sc_addr_m: .long 0x80020070"
	);
}

void alias_realloc() {
	__asm__ volatile(
		"mov.l sc_addr_r, r2; "
		"mov.l 3f, r0; "
		"jmp @r2; "
		"nop; "
		"3: .long 0x1f46 \n"
		"sc_addr_r: .long 0x80020070"
	);
}

void free(void *p) __attribute__((weak, alias("alias_free")));
void *malloc(size_t sz) __attribute__((weak, alias("alias_malloc")));
void *realloc(void *p, size_t sz) __attribute__((weak, alias("alias_realloc")));
```

Unfortunately, including stdlib.h multiple times (e.g. by including string.h and stdlib.h) causes the following error when compiling a project:
```
/usr/bin/sh3eb-elf-ld: string.o (symbol from plugin): in function `_alias_free':
(.text+0x0): multiple definition of `_alias_free'; main.o:main.c:(.text.alias_free+0x0): first defined here
/usr/bin/sh3eb-elf-ld: string.o (symbol from plugin): in function `_alias_free':
(.text+0x0): multiple definition of `_alias_malloc'; main.o:main.c:(.text.alias_malloc+0x0): first defined here
/usr/bin/sh3eb-elf-ld: string.o (symbol from plugin): in function `_alias_free':
(.text+0x0): multiple definition of `_alias_realloc'; main.o:main.c:(.text.alias_realloc+0x0): first defined here
```

I'm not entirely sure how to fix this - you may have some ideas.

**Comment by tari** [comment]
The inline assembly versions and alias prototypes would completely replace the existing `sys_free` and friends syscall definitions: putting the entire code block into a single .c file and build it as part of libfxcg, then provide the regular prototypes in the header.

free.c:
```c
__attribute__((naked)) void sys_free() {
	__asm__ volatile(
		"mov.l 1f, r2; "
		"mov.l 2f, r0; "
		"jmp @r2; "
		"nop; "
		"1: .long 0x80020070 \n"
		"2: .long 0x1f42"
	);
}

void free(void *p) __attribute__((weak, alias("alias_free")));
```

stdlib.h:
```c
void free(void *p);
```

**Comment by dr-carlos** [comment]
> The inline assembly versions and alias prototypes would completely replace the existing `sys_free` and friends syscall definitions: put the entire code block into a single .c file and build it as part of libfxcg, then provide the regular prototypes in the header.

I have done this with all three functions, but when compiling a project that uses stdlib.h, the following error occurs:
```
/tmp/cccEKD3D.s: Assembler messages:
/tmp/cccEKD3D.s:50: Error: misaligned data
/tmp/cccEKD3D.s:50: Error: offset to unaligned destination
```

**Comment by tari** [comment]
Having experimented with this myself now, I think the weak alias idea just won't work. But it seems like we could simply have `free` delegate to `sys_free` but itself be weak:

```c
void free(void *p) __attribute__((weak)) {
    return sys_free(p);
}
```
