### ISSUE TITLE
not able to compile example on windows

### ISSUE THREAD

**Issue by Japie3krekel** [Jonimoose/libfxcg#47]
i ran the make file as admin with powershell  but it gives an error that it doesnt have access to something. how can i fix this ??

the error is:
PS F:\PrizmSDK-win-0.5\projects\example> .\make

F:\PrizmSDK-win-0.5\projects\example>..\..\bin\make.exe
sh3eb-elf-gcc -MMD -MP -MF F:/PrizmSDK-win-0.5/projects/example/build/example.d -Os -Wall -mb -m4a-nofpu -mhitachi -nostdlib   -IF:/PrizmSDK-win-0.5/projects/example/build -IF:/PrizmSDK-win-0.5/include -ffunction-sections -fdata-sections  -c F:/PrizmSDK-win-0.5/projects/example/src/example.c -o example.o
process_begin: CreateProcess(F:\PrizmSDK-win-0.5\bin\sh3eb-elf-gcc.exe, sh3eb-elf-gcc -MMD -MP -MF F:/PrizmSDK-win-0.5/projects/example/build/example.d -Os -Wall -mb -m4a-nofpu -mhitachi -nostdlib -IF:/PrizmSDK-win-0.5/projects/example/build -IF:/PrizmSDK-win-0.5/include -ffunction-sections -fdata-sections -c F:/PrizmSDK-win-0.5/projects/example/src/example.c -o example.o, ...) failed.
make (e=5): Toegang geweigerd (access not allowed).
make[1]: *** [F:/PrizmSDK-win-0.5/toolchain/prizm_rules:64: example.o] Error 5
make: *** [Makefile:104: all] Error 2

**Comment by tari** [comment]
It sounds like permissions on your files are wonky, or maybe an antivirus is getting in the way? I think this error is `make` complaining that it's not allowed to execute `sh3eb-elf-gcc`.

I can get the same error if I deny execute permissions on that file:
![Windows properties page for sh3eb-elf-gcc.exe](https://user-images.githubusercontent.com/506181/89230993-b9f2ff00-d627-11ea-8a69-0e2bb8672e21.png)

So you probably need to check that your permissions are set appropriately.

**Comment by gerardjensen** [comment]
I had a similar error because the path to the project folder contained spaces. It didn't work just to put the project file in C.\ beacuse there were some permission errors.

At the end I had to create a new user without spaces on its name and copile thourgh there with the project folder being in the Desktop folder of that user.
