### ISSUE TITLE
Error compiling example

### ISSUE THREAD

**Issue by darkroasted** [Jonimoose/libfxcg#48]
Hey guys, 

So I wanted to start getting into making apps for my prism calculator. However I got an error when following this guide on how to use this tool (guide : [https://github.com/tswilliamson/PrizmSDK/blob/master/docs/howto-windows.md](https://github.com/tswilliamson/PrizmSDK/blob/master/docs/howto-windows.md))

After I cd into the directory of the example project and then run `.\make` i get an error with something about an image.

this is the output of my powershell terminal...

```PS Z:\PrizmSDK-win-0.5\projects\example> .\make

Z:\PrizmSDK-win-0.5\projects\example>..\..\bin\make.exe
mkg3a -n basic:example -i uns:../unselected.bmp -i sel:../selected.bmp Z:/PrizmSDK-win-0.5/projects/example/example.bin Z:/PrizmSDK-win-0.5/projects/example/example.g3a
Error reading image: Unexpected EOF
Failed to parse option: `uns:../unselected.bmp`.  See previous error.

Usage: mkg3a [OPTION] input-file [output-file]

  -i (uns|sel):file
     Load unselected/selected icon from file
  -n lc:name
     Set localized name for language code
  -V ver
     Set version string
  -v
     Show version and license information then exit

Valid values for lc are basic, internal, en, es, de, fr, pt and zh.
Empty lc is an alias for basic.  Unset names will be derived from
basic, which defaults to output file name.

Multiple -n or -i options will all be applied, with the last
specified option overriding previous ones with the same key.
make[1]: *** [Z:/PrizmSDK-win-0.5/toolchain/prizm_rules:80: Z:/PrizmSDK-win-0.5/projects/example/example.g3a] Error 1
make: *** [Makefile:104: all] Error 2
PS Z:\PrizmSDK-win-0.5\projects\example>
```

I have also tried running this as an administrator but that didn't help. 

Any help is greatly appreciated, Thanks

**Comment by tari** [comment]
You hit a bug in mkg3a that was fixed, but there hasn't (hadn't) been a new release made here.

You can grab [v0.5.1](https://github.com/Jonimoose/libfxcg/releases/tag/v0.5.1) (which I've just tagged) to get a newer mkg3a which has that fixed. I'm confident this will fix your problem, but feel free to reopen if I'm wrong.

**Comment by darkroasted** [comment]
Great thanks, its working now. 

Just one more question. I was not able to create my own icons for on the calculators homescreen replacing the selected.bmp and unselected.bmp. I tried using photoshop and some other online tools. However with no success. So what software and settings or workflow do you guys use? 

When compiling I now get this error: 
'Error reading image: Unsupported color depth (must be 24 bpp)'

Any tips or help is greatly appreciated!

**Comment by Firefluid** [comment]
The .BMP icons must be exported with truecolor (24-bit, 8 bits per channel, and no alpha. In GIMP during export: Advanced Options > 24 bits > R8 G8 B8). Icons can also be exported in PNG format if your mkg3a was built with libpng support (though, I don't know whether it is in the pre-built [v0.5.1](https://github.com/Jonimoose/libfxcg/releases/tag/v0.5.1)). And just in case you need it, there are some Icon Style Guidelines on the Prizm Wiki: https://prizm.cemetech.net/index.php?title=Addin_Usability_Guidelines#Icon_Guidelines

Hope that helps!

**Comment by tari** [comment]
The provided mkg3a binary does have PNG support built in, so that's the easiest way to generate an image (make it a PNG, rather than a BMP).
