### ISSUE TITLE
Cant use sprintf, strcat and atoi functions

### ISSUE THREAD

**Issue by WhlIlte** [Jonimoose/libfxcg#49]
I have `#include <stdio.h> #include <stdlib.h> #include <string.h>` imported, so I should be able to use them with out problems, but when I try to compile, I get a hundred of errors saying that _strlen and _memcpy, references are undefined.
If I comment the functions, everything works fine.

Full error log:
https://pastebin.com/XaRaHifr

**Comment by tari** [comment]
Without investigating further (yet), I suspect this is similar to #46.

**Comment by tari** [comment]
Are you using 0.5.1, or an earlier release? I think memcpy should work after d1d30ced16414206d705519d939a189c028fdc91.

**Comment by tari** [comment]
Without any further info, I assume this has been fixed in a newer release, either by the noted commit above or maybe #55.
