### ISSUE TITLE
Prototypes are provided for unimplemented math functions

### ISSUE THREAD

**Issue by Pawl-Patrol** [Jonimoose/libfxcg#54]
While playing around with the math functions, I ran into a weird issue. As a simple example, consider these two files. Both files are compiled with the example Makefile.

example1.cpp - This does compile without any issues.
```cpp
#include <fxcg/keyboard.h>
#include <fxcg/display.h>
#include <fxcg/misc.h>
#include <math.h>

int main()
{
    double result = sin(1.45f);

    // This just prints me the fraction of the result.
    char buffer[20] = "  ";
    itoa(result*100000, (unsigned char*)buffer + 2);
    PrintXY(1, 1, buffer, TEXT_MODE_NORMAL, TEXT_COLOR_BLACK);

    int key;
    while (true)
    {
        GetKey(&key);
    }

    return 0;
}
```

example2.cpp - This throws me an error.
```cpp
#include <fxcg/keyboard.h>
#include <fxcg/display.h>
#include <fxcg/misc.h>
#include <math.h>

double copy_of_sin(double x)
{
    return sin(x);
}

int main()
{
    double result = copy_of_sin(1.45f);

    // This just prints me the fraction of the result.
    char buffer[20] = "  ";
    itoa(result*100000, (unsigned char*)buffer + 2);
    PrintXY(1, 1, buffer, TEXT_MODE_NORMAL, TEXT_COLOR_BLACK);

    int key;
    while (true)
    {
        GetKey(&key);
    }

    return 0;
}
```
Here's the command line output when trying to compile it:
```
C:\Users\Pawl\Documents\PrizmSDK\projects\test>..\..\bin\make.exe
sh3eb-elf-g++  main.o -mb -m4a-nofpu -mhitachi -nostdlib -TC:/Users/Pawl/Documents/PrizmSDK/toolchain/prizm.x -Wl,-static -Wl,-gc-sections  -LC:/Users/Pawl/Documents/PrizmSDK/lib -lfxcg -lc -lgcc -o C:/Users/Pawl/Documents/PrizmSDK/projects/test/test.bin
c:/users/pawl/documents/prizmsdk/bin/../lib/gcc/sh3eb-elf/9.3.0/../../../../sh3eb-elf/bin/ld.exe: main.o: in function `copy_of_sin(double)':
main.cpp:(.text._Z11copy_of_sind+0x8): undefined reference to `_sin'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [C:/Users/Pawl/Documents/PrizmSDK/toolchain/prizm_rules:83: C:/Users/Pawl/Documents/PrizmSDK/projects/test/test.bin] Error 1
make: *** [Makefile:104: all] Error 2
```

I don't understand why the second file has an `undefined reference` error when it worked in the first example. Am I missing something? The first compiled example even gives me the correct fraction of sin(1.45). Makes no sense to me.
I've tried both version 0.5 and version 0.5.1 from the release page. 
Thanks in advance.

**Comment by tari** [comment]
In the former example the compiler is able to optimize the call to `sin` out, since it's constant and trivially inlined. In the latter (with no particular optimization options), it doesn't.

We don't actually provide implementations of math functions like this, so it's expected that you get a link-time failure when trying to use them. That does however raise the question of why we have the prototypes, and suggests that maybe they should be removed.

**Comment by Pawl-Patrol** [comment]
Thank you for the quick answer and explanation. I'll just implement these functions by myself then.

**Comment by Heath123** [comment]
So is there any way to use these functions?

**Comment by Pawl-Patrol** [comment]
I recommend using something like `fdlibm` if you don't want to implement these functions yourself. Alternatively approximation can be done using numerical procedures like Taylor series or Newton's method.

**Comment by Heath123** [comment]
Will that make use of the hardware as well as the one in GCC (if it's even possible to make that work) would?

**Comment by Heath123** [comment]
Well it looks like it's used in Chromium, Firefox, Android and some other things so it's probably fast enough, thank you

**Comment by Pawl-Patrol** [comment]
No. Would be great to figure out where the math functions are located but with this approach we would just duplicate them (tell me if you found a way! :).

FYI the calculator has no FPU unit according to the [wiki](https://prizm.cemetech.net/index.php?title=Technical_Info). So there's probably no hardware accelerated math from my understanding.

**Comment by Heath123** [comment]
Would it make any sense to include fdlibm in libfxcg?

**Comment by Pawl-Patrol** [comment]
Sure. Best short-term solution for math functions.

**Comment by tari** [comment]
Reopening because we probably shouldn't provide prototypes for functions that we don't provide implementations for: these prototypes should be deleted.

It's a little annoying because compilers recognize these functions and can in some situations evaluate them at compile-time, but in that case a program using them would depend on compile-time evaluation and may as well hard-code the values it wants.
