### ISSUE TITLE
White screen in starfield example on fx-CG50

### ISSUE THREAD

**Issue by dr-carlos** [Jonimoose/libfxcg#66]
Compiling and running the Starfield example produces a white screen which can be escaped only via the menu key on fx-CG50 AU.
I'm pretty new so not sure where the issue is, but compiling produces warnings about a 'memset' function.

**Comment by tari** [comment]
Looks like that example incorrectly uses a hardcoded VRAM address in `DrawPixelGray` and `DrawPixelSet`. It should call `GetVRAMAddress` instead.

The changes in https://github.com/Jonimoose/libfxcg/pull/67 should make it work, if you can try that for me.

**Comment by dr-carlos** [comment]
Thank you, the example now works.
It has a white frame around it when running, but it looks like a starfield to me.
