### ISSUE TITLE
Bytecode stream generated with LTO version 9.0 instead of the expected 11.0

### ISSUE THREAD

**Issue by Heath123** [Jonimoose/libfxcg#73]
Sometimes I get:
```
lto1: fatal error: bytecode stream in file '/home/heath/PrizmSDK-win-0.5.2/lib/libc.a' generated with LTO version 9.0 instead of the expected 11.0
```
whether LTO is on or off. Do I need to use GCC 9.0/compile libfxcg myself?

**Comment by dr-carlos** [comment]
> Sometimes I get:
> 
> ```
> lto1: fatal error: bytecode stream in file '/home/heath/PrizmSDK-win-0.5.2/lib/libc.a' generated with LTO version 9.0 instead of the expected 11.0
> ```
> 
> whether LTO is on or off. Do I need to use GCC 9.0/compile libfxcg myself?

This probably means that libfxcg was compiled with GCC 9.0, but you are using GCC 11.0.
This just means you will need to compile libfxcg yourself.
Assuming you're on Linux/Mac, you should just need to go into the top directory of libfxcg, run `make clean` and `make`.

**Comment by Heath123** [comment]
I thought so, but shouldn't this be fixable by turning off LTO? I'll have to build it myself but first I need to work out how to get `sh3eb-elf-gcc-ar`

**Comment by dr-carlos** [comment]
> I thought so, but shouldn't this be fixable by turning off LTO? I'll have to build it myself but first I need to work out how to get `sh3eb-elf-gcc-ar`

Yeah, I think the error is because libfxcg was built with LTO, so this will happen. It should probably be updated to a newer GCC version, but I'm not sure when Tari will do this.
`sh3eb-elf-gcc-ar` should come with `sh3eb-elf-gcc` on your distro?

**Comment by tari** [comment]
What actual version of GCC do you have? Did you build it yourself?

**Comment by Heath123** [comment]
> What actual version of GCC do you have? Did you build it yourself?

Looks like I got it from here: https://aur.archlinux.org/packages/sh-elf-gcc-casio

I guess I should just compile it myself

**Comment by Heath123** [comment]
```
$ sh3eb-elf-gcc --version
sh3eb-elf-gcc (GCC) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by tari** [comment]
It certainly does look like your GCC's bitcode is incompatible with whatever version your libfxcg binaries were built with. I notice you're using a windows SDK build on something that's not Windows, so probably the easiest thing to do is check out a copy of this repository and build your own `.a` files (you should be able to simply run `make` in the root of the repository).

**Comment by Heath123** [comment]
> It certainly does look like your GCC's bitcode is incompatible with whatever version your libfxcg binaries were built with. I notice you're using a windows SDK build on something that's not Windows, so probably the easiest thing to do is check out a copy of this repository and build your own `.a` files (you should be able to simply run `make` in the root of the repository).

I used the Windows one because everything was already set up into a nice structure and it also seemed to work with Linux. I suppose it's expected that this would happen if I try to use the Windows build with a different compiler on Linux, so I'll close this.

I compiled it myself, and it does _seem_ to work now!

**Comment by Heath123** [comment]
Actually there are precompiled library files for Linux too so it might make sense to provide them for different compiler versions?
