### ISSUE TITLE
What are _free_r, _malloc_r, _realloc_r, and _calloc_r?

### ISSUE THREAD

**Issue by dr-carlos** [Jonimoose/libfxcg#98]
These seem to be versions of free, malloc, calloc, and realloc but using `struct _reent *ptr`, which is not defined anywhere.

I'm interested to know if they are of any use or if they should be deleted, as they don't seem to have any references to them, and all the implementations just disregard the `struct _reent *ptr` which seems to be their only use.

**Comment by tari** [comment]
It appears to be a newlib primate thing, where some newlib implementations of reentrant functions use it and at least some platforms do the same thing (ignore the reentrancy struct) presumably because their malloc is already reentrant.

Given it's a private newlib API, I wouldn't mind deleting it.

**Comment by dr-carlos** [comment]
I've created PR #100 to remove the functions.
